name: dockerlab02

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install requirements
        run: |
          pip install -r requirements.txt
          
      - name: check by pylint
        run: |
          pip install pylint==2.17.4
          pylint --disable=R,C main.py
          
      - name: Docker Login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.USERNAME_HUB }}
          password: ${{ secrets.PASSED_HUB }}
    
      - name: Build and push
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          file: ./Dockerfile.txt
          push: true
          tags: laitielly/knapsack01:latest



